package com.meritscreen.feature.child.data

import com.meritscreen.core.common.domain.AgeBand
import com.meritscreen.core.common.domain.LearningResource
import com.meritscreen.core.common.domain.StaticLearningResourceCatalog
import com.meritscreen.core.firebase.ai.FirebaseLearningResourceClient
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Repository orchestrating instant offline-ready learning resources and dynamic Firebase AI enhancements.
 */
@Singleton
class LearningResourceRepository @Inject constructor(
    private val aiClient: FirebaseLearningResourceClient,
) {
    /**
     * Emits the high-quality static baseline immediately (0ms delay), then emits the
     * AI-enriched learning resource once generated by Firebase AI.
     */
    fun getResourceStream(
        prompt: String,
        wrongAnswerText: String,
        correctAnswerText: String,
        topic: String,
        conceptId: String,
        conceptTitle: String,
        ageBand: AgeBand = AgeBand.AGE_7_TO_9,
    ): Flow<LearningResource> = flow {
        // Step 1: Emit instant static baseline so UI opens with 0ms delay
        val baseline = StaticLearningResourceCatalog.getFor(conceptId, topic, conceptTitle)
        emit(baseline)

        // Step 2: Query Firebase AI for personalized explanation
        val aiEnhanced = runCatching {
            aiClient.generateOrFetchResource(
                prompt = prompt,
                wrongAnswerText = wrongAnswerText,
                correctAnswerText = correctAnswerText,
                topic = topic,
                conceptId = conceptId,
                conceptTitle = conceptTitle,
                ageBand = ageBand,
            )
        }.getOrNull()

        if (aiEnhanced != null) {
            emit(aiEnhanced)
        }
    }

    /**
     * Instant lookup without network call.
     */
    fun getStaticBaseline(conceptId: String, topic: String, conceptTitle: String = ""): LearningResource {
        return StaticLearningResourceCatalog.getFor(conceptId, topic, conceptTitle)
    }
}
